plugins {
	id 'jadx-library'
	id("net.ltgt.errorprone") version "2.0.2"
}

dependencies {
	api(project(':jadx-plugins:jadx-plugins-api'))

	implementation 'com.google.code.gson:gson:2.9.1'

	// TODO: move resources decoding to separate plugin module
	implementation 'com.android.tools.build:aapt2-proto:7.3.1-8691043'
	implementation 'com.google.protobuf:protobuf-java:3.21.8' // forcing latest version

	testImplementation 'org.apache.commons:commons-lang3:3.12.0'

	testImplementation(project(':jadx-plugins:jadx-dex-input'))
	testRuntimeOnly(project(':jadx-plugins:jadx-smali-input'))
	testRuntimeOnly(project(':jadx-plugins:jadx-java-convert'))
	testRuntimeOnly(project(':jadx-plugins:jadx-java-input'))
	testRuntimeOnly(project(':jadx-plugins:jadx-raung-input'))

	testImplementation 'org.eclipse.jdt:ecj:3.31.0'
	testImplementation 'tools.profiler:async-profiler:1.8.3'

	compileOnly "com.google.code.findbugs:jsr305:3.0.2"
	errorprone "com.google.errorprone:error_prone_core:2.3.2"
	errorproneJavac "com.google.errorprone:javac:9+181-r4173-1"

	annotationProcessor "com.uber.nullaway:nullaway:0.10.8"
	annotationProcessor "edu.ucr.cs.riple.annotator:annotator-scanner:1.3.6-alpha-5"
    compileOnly "com.uber.nullaway:nullaway-annotations:0.10.10"
    compileOnly "org.jspecify:jspecify:0.3.0"
}

test {
	exclude '**/tmp/*'
}

import net.ltgt.gradle.errorprone.CheckSeverity

def scanner_path =  "${rootDir.getAbsolutePath()}" +"/out/scanner.xml"
def nullaway_path =  "${rootDir.absolutePath}/out/checker.xml"
def annotator_mode = (System.getenv("ANNOTATOR_MODE") != null)
def nullaway_off = (System.getenv("NULLAWAY_OFF") != null)

tasks.withType(JavaCompile) {
	// remove the if condition if you want to run NullAway on test code
	if (!name.toLowerCase().contains("test")) {
		options.errorprone.disableAllChecks = true
		options.errorprone {
            check("NullAway", nullaway_off ? CheckSeverity.OFF : CheckSeverity.ERROR)
            check("AnnotatorScanner", annotator_mode ? CheckSeverity.ERROR : CheckSeverity.OFF)
			option("NullAway:AnnotatedPackages", "jadx.core")
            option("NullAway:SerializeFixMetadata", annotator_mode ? "true" : "false")
            option("NullAway:FixSerializationConfigPath", nullaway_path)
            option("AnnotatorScanner:ConfigPath", scanner_path)
		}
		options.compilerArgs << "-Xmaxerrs" << "100000"
	}
}
